const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const html=fs.readFileSync(__dirname+'/fourier-synthesis.html','utf8');const code=html.match(/<script id="fourier-model">([\s\S]*?)<\/script>/)[1];const m=vm.runInNewContext(code+';FourierModel;');
const N=128,TAU=2*Math.PI,near=(a,b,tol=1e-9)=>assert(Math.abs(a-b)<tol,`${a} vs ${b}`),points=fn=>Array.from({length:N},(_,i)=>fn(TAU*i/N));
let maxReconstruction=0,maxParseval=0,maxEnergyRmse=0,maxSingleLeakage=0;
const constant=points(()=>({x:2,y:-3})),dc=m.dft(constant);near(dc[0].re,2);near(dc[0].im,-3);dc.slice(1).forEach(c=>near(c.amplitude,0));
for(const k of [-63,-7,1,19,64]){const p=points(t=>({x:Math.cos(k*t+.3),y:Math.sin(k*t+.3)})),c=m.dft(p),one=c.find(c=>c.k===k);near(one.re,Math.cos(.3));near(one.im,Math.sin(.3));for(const other of c.filter(c=>c.k!==k)){maxSingleLeakage=Math.max(maxSingleLeakage,other.amplitude);near(other.amplitude,0);}near(m.rmse(p,[one]),0);}
const cos=m.dft(points(t=>({x:Math.cos(5*t+.4),y:0})));const plus=cos.find(c=>c.k===5),minus=cos.find(c=>c.k===-5);near(plus.re,minus.re);near(plus.im,-minus.im);near(plus.amplitude,.5);
for(const name of ['circle','square','star','asymmetric']){const p=m.preset(name),c=m.dft(p);assert.equal(p.length,N);assert.equal(new Set(c.map(c=>c.k)).size,N);assert.equal(c.at(-1).k,64);const energy=p.reduce((s,p)=>s+p.x*p.x+p.y*p.y,0)/N,frequencyEnergy=c.reduce((s,c)=>s+c.amplitude**2,0);maxParseval=Math.max(maxParseval,Math.abs(energy-frequencyEnergy));near(energy,frequencyEnergy);let previous=Infinity;for(let n=1;n<=N;n++){const error=m.rmse(p,c.slice(0,n)),omitted=c.slice(n).reduce((s,c)=>s+c.amplitude**2,0);assert(error<=previous+1e-12);near(error*error,omitted);maxEnergyRmse=Math.max(maxEnergyRmse,Math.abs(error*error-omitted));previous=error;}p.forEach((p,i)=>{const q=m.synthesize(c,i/N);maxReconstruction=Math.max(maxReconstruction,Math.hypot(p.x-q.x,p.y-q.y));});}
assert(maxReconstruction<1e-9);
const square=[{x:0,y:0},{x:1,y:0},{x:1,y:1},{x:0,y:1},{x:0,y:0}];const res=m.resample(square,8);assert.equal(res.length,8);near(res[1].x,.5);near(res[7].x,0);near(res[7].y,.5);assert(Math.hypot(res[0].x-res[7].x,res[0].y-res[7].y)>.1);const short=m.resample([square[0],square[0],{x:1e-12,y:0},...square.slice(1)],8);res.forEach((p,i)=>{near(p.x,short[i].x);near(p.y,short[i].y);});
assert.throws(()=>m.resample(Array(20).fill({x:0,y:0})));assert.throws(()=>m.resample([{x:0,y:0},{x:.001,y:0},{x:0,y:.001}]));assert.throws(()=>m.resample([{x:NaN,y:0},...square]));const norm=m.normalize(res);near(norm.reduce((s,p)=>s+p.x,0),0);near(norm.reduce((s,p)=>s+p.y,0),0);near(Math.max(...norm.map(p=>Math.hypot(p.x,p.y))),1);
console.log(JSON.stringify({status:'PASS',N,maxReconstruction,maxParseval,maxEnergyRmse,maxSingleLeakage,tolerance:1e-9,checks:'DC, signed single-frequency circles, Nyquist uniqueness, real cosine conjugacy, full inverse, Parseval, every component count RMSE monotonicity/omitted energy, wrap, repeated endpoint, short segments, invalid input, centering and scale'},null,2));
