const {chromium}=require('/home/bayta/.cache/ms-playwright-go/1.57.0/package');
const fs=require('node:fs'),http=require('node:http'),assert=require('node:assert/strict');
const server=require('../tests/static-server.cjs')();
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({executablePath:'/snap/chromium/current/usr/lib/chromium-browser/chrome',headless:true,env:{...process.env,FONTCONFIG_FILE:'/tmp/abyssal-fonts.conf',LD_LIBRARY_PATH:'/snap/chromium/current/usr/lib/x86_64-linux-gnu:/snap/gnome-46-2404/current/usr/lib/x86_64-linux-gnu'},args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-dev-shm-usage']});
try{const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});const url=`http://127.0.0.1:${server.address().port}/fourier-synthesis/fourier-synthesis.html`;await page.goto(url);await page.waitForFunction(()=>window.__fourier,{timeout:90000});const state=()=>page.evaluate(()=>__fourier.state());
await page.waitForTimeout(1500);assert((await state()).t>0);await page.click('#pause');const frozen=await state();await page.waitForTimeout(300);assert.equal((await state()).t,frozen.t);await page.click('#auto');const ct=(await state()).cameraTime;await page.waitForTimeout(200);assert.equal((await state()).cameraTime,ct);await page.click('#pause');await page.waitForTimeout(300);assert((await state()).cameraTime>ct);await page.click('#pause');await page.click('#auto');const camera=await page.evaluate(()=>__fourier.camera.position.toArray());await page.mouse.move(600,300);await page.waitForTimeout(100);assert.deepEqual(await page.evaluate(()=>__fourier.camera.position.toArray()),camera);
await page.click('#reset');assert.equal((await state()).t,0);await page.click('#step');assert.equal((await state()).t,1/128);assert((await state()).paused);
for(const name of ['circle','square','star','asymmetric']){await page.selectOption('#preset',name);assert.equal((await state()).t,0);for(const value of [1,128]){await page.locator('#count').evaluate((e,v)=>{e.value=v;e.dispatchEvent(new Event('input',{bubbles:true}));},value);assert.equal((await state()).count,value);if(value===128)assert((await state()).error<1e-9);}}
await page.locator('#count').evaluate(e=>{e.value=15;e.dispatchEvent(new Event('input'));});await page.selectOption('#frequency','-3');assert((await page.textContent('#phase')).includes('k = -3'));for(const id of ['circles','vectors','original']){await page.uncheck('#'+id);await page.check('#'+id);}await page.selectOption('#period','4');await page.selectOption('#speed','2');await page.evaluate(()=>__fourier.advance(.05));assert(Math.abs((await state()).t-.025)<1e-12);await page.evaluate(()=>__fourier.advance(100));assert((await state()).t<.06);
await page.click('#view');assert((await state()).timeView);await page.click('#pause');await page.waitForTimeout(1500);await page.click('#pause');await page.screenshot({path:__dirname+'/desktop-time.png'});await page.click('#view');await page.screenshot({path:__dirname+'/desktop-plane.png'});
await page.click('#clear');const before=await state();await page.click('#apply');assert.equal((await state()).error,before.error);assert((await page.textContent('#draw-status')).includes('유지'));
const draw=async()=>{const b=await page.locator('#pad').boundingBox();await page.mouse.move(b.x+b.width*.2,b.y+b.height*.2);await page.mouse.down();await page.mouse.move(b.x+b.width*.8,b.y+b.height*.2,{steps:12});await page.mouse.move(b.x+b.width*.7,b.y+b.height*.8,{steps:12});await page.mouse.move(b.x+b.width*.2,b.y+b.height*.6,{steps:12});await page.mouse.up();await page.click('#apply');assert.equal(await page.inputValue('#preset'),'custom');assert.equal((await state()).t,0);};await draw();
// Chromium can round scroll offsets by a fraction of a CSS pixel. Allow the same 1px tolerance on both edges.
for(const size of [{width:390,height:844},{width:844,height:390}]){await page.setViewportSize(size);assert(await page.evaluate(()=>document.documentElement.scrollWidth===innerWidth));for(const id of ['pause','reset','step','apply','auto','view','count','preset']){await page.locator('#'+id).scrollIntoViewIfNeeded();const b=await page.locator('#'+id).boundingBox();assert(b.x>=0&&b.x+b.width<=size.width+1,id);assert(b.y>=-1&&b.y+b.height<=size.height+1,id+JSON.stringify({size,b}));}await draw();await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:__dirname+`/mobile-${size.width}.png`});}
await page.setViewportSize({width:390,height:844});await page.locator('#pad').scrollIntoViewIfNeeded();const circleBox=await page.locator('#pad').boundingBox();await page.mouse.move(circleBox.x+circleBox.width/2+40,circleBox.y+circleBox.height/2);await page.mouse.down();for(let i=1;i<=64;i++)await page.mouse.move(circleBox.x+circleBox.width/2+40*Math.cos(i*Math.PI/32),circleBox.y+circleBox.height/2+40*Math.sin(i*Math.PI/32));await page.mouse.up();await page.click('#apply');const circleRatio=await page.evaluate(()=>{const p=__fourier.samples();return (Math.max(...p.map(p=>p.x))-Math.min(...p.map(p=>p.x)))/(Math.max(...p.map(p=>p.y))-Math.min(...p.map(p=>p.y)));});assert(Math.abs(circleRatio-1)<.01,'drawing must preserve equal CSS x/y lengths');const b=await page.locator('#pad').boundingBox();const session=await page.context().newCDPSession(page);await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:b.x+20,y:b.y+20}]});await session.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:b.x+100,y:b.y+30}]});await session.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:b.x+150,y:b.y+90}]});await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.click('#apply');assert((await page.textContent('#draw-status')).includes('적용했습니다'));
await page.locator('#pad').dispatchEvent('pointercancel',{pointerId:1});assert.equal((await state()).drawingCount,0);
await page.emulateMedia({reducedMotion:'reduce'});assert((await state()).paused);assert(!(await state()).auto);await page.reload();await page.waitForFunction(()=>window.__fourier);assert((await state()).paused);assert(!(await state()).auto);
await page.evaluate(()=>{__fourier.advance(.004);document.dispatchEvent(new Event('visibilitychange'));});assert.equal((await state()).accumulator,0);
await page.evaluate(()=>window.dispatchEvent(new PageTransitionEvent('pagehide',{persisted:true})));const frame=await page.evaluate(()=>__fourier.renderer.info.render.frame);await page.waitForTimeout(120);assert.equal(await page.evaluate(()=>__fourier.renderer.info.render.frame),frame);await page.evaluate(()=>window.dispatchEvent(new PageTransitionEvent('pageshow',{persisted:true})));await page.waitForTimeout(150);assert(await page.evaluate(()=>__fourier.renderer.info.render.frame)>frame);
const rendering=await page.evaluate(()=>({frames:__fourier.renderer.info.render.frame,calls:__fourier.renderer.info.render.calls,geometries:__fourier.renderer.info.memory.geometries,contextLost:__fourier.renderer.getContext().isContextLost()}));assert(!rendering.contextLost);await page.evaluate(()=>window.dispatchEvent(new PageTransitionEvent('pagehide',{persisted:false})));assert((await state()).disposed);assert.equal(await page.evaluate(()=>__fourier.renderer.info.memory.geometries),0);assert.deepEqual(errors,[]);
const fail=await browser.newPage();await fail.route('https://unpkg.com/**',route=>route.abort());await fail.goto(url);await fail.waitForSelector('#error:not([hidden])');await fail.close();
const lost=await browser.newPage();await lost.goto(url);await lost.waitForFunction(()=>window.__fourier);await lost.evaluate(()=>__fourier.renderer.domElement.dispatchEvent(new Event('webglcontextlost',{cancelable:true})));await lost.waitForSelector('#error:not([hidden])');assert(await lost.evaluate(()=>__fourier.state().disposed));await lost.close();
console.log(JSON.stringify({status:'PASS',rendering,circleRatio,errors,checks:'real RAF, presets, 1/128 components, phase, toggles, pause/camera, resume, step/reset, 2x clock, long-delta cap, time view, desktop/mobile draw, real touch input, invalid apply, pointercancel, responsive scrolling, reduced-motion initial/change, visibility, simulated BFCache lifecycle, GPU disposal, CDN and WebGL failure'},null,2));
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
