const {chromium}=require('/home/bayta/.cache/ms-playwright-go/1.57.0/package');
const fs=require('fs'),http=require('http'),assert=require('assert');
const file=__dirname+'/pid-servo.html';
const server=http.createServer((req,res)=>{if(req.url==='/favicon.ico'){res.writeHead(204);return res.end();}res.setHeader('Content-Type','text/html');res.end(fs.readFileSync(file));});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({executablePath:'/snap/chromium/current/usr/lib/chromium-browser/chrome',headless:true,env:{...process.env,FONTCONFIG_FILE:'/tmp/abyssal-fonts.conf',LD_LIBRARY_PATH:'/snap/chromium/current/usr/lib/x86_64-linux-gnu:/snap/gnome-46-2404/current/usr/lib/x86_64-linux-gnu'},args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-dev-shm-usage']});
try{const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});const url=`http://127.0.0.1:${server.address().port}/pid-servo/pid-servo.html`;await page.goto(url);await page.waitForFunction(()=>window.pidDemo,null,{timeout:90000});const snapshot=()=>page.evaluate(()=>pidDemo.snapshot());await page.waitForTimeout(1200);assert((await snapshot()).s.t>0);assert((await snapshot()).frames>2);await page.screenshot({path:'/tmp/pid-desktop.png'});console.log('actual RAF ready',await snapshot());
await page.click('#pause');await page.click('#auto');let a=await snapshot();await page.waitForTimeout(300);let b=await snapshot();assert.equal(a.s.t,b.s.t);assert.equal(a.cameraTime,b.cameraTime);await page.click('#pulse');assert.equal((await snapshot()).pulseLeft,100);await page.click('#step');b=await snapshot();assert(Math.abs(b.s.t-a.s.t-.005)<1e-10);assert.equal(b.s.d,2);assert.equal(b.pulseLeft,99);await page.evaluate(()=>{for(let i=0;i<99;i++)document.querySelector('#step').click();});assert.equal((await snapshot()).pulseLeft,0);assert.equal((await snapshot()).s.d,2);await page.click('#step');assert.equal((await snapshot()).s.d,0);await page.click('#reset');assert.equal((await snapshot()).s.t,0);assert.equal((await snapshot()).pulseLeft,0);
await page.selectOption('#speed','2');await page.click('#pause');await page.waitForTimeout(500);assert((await snapshot()).s.t>0);await page.click('#pause');await page.click('#front');a=await snapshot();await page.waitForTimeout(100);a=await snapshot();await page.mouse.move(500,250);await page.waitForTimeout(100);assert.deepEqual((await snapshot()).camera,a.camera);await page.click('#oblique');
for(const preset of ['p','pi','critical','overshoot','saturation','windup','pid']){await page.selectOption('#preset',preset);assert.equal((await snapshot()).s.t,0);await page.click('#step');assert((await snapshot()).s.t>0);}await page.selectOption('#preset','pid');await page.click('#step');a=await snapshot();await page.locator('#target').fill('0.5');await page.locator('#target').dispatchEvent('input');b=await snapshot();assert.equal(a.s.x,b.s.x);assert.equal(a.s.v,b.s.v);assert.equal(b.s.I,0);assert.equal(b.p.target,.5);
for(const id of ['kp','ki','kd']){await page.locator('#'+id).fill('5');await page.locator('#'+id).dispatchEvent('input');assert.equal((await snapshot()).p[id],5);}for(const [id,val]of [['mass','2'],['drag','1'],['limit','4']]){await page.locator('#'+id).fill(val);await page.locator('#'+id).dispatchEvent('input');assert.equal((await snapshot()).s.t,0);assert.equal((await snapshot()).p[id],+val);}await page.click('#aw');assert.equal((await snapshot()).p.aw,false);await page.selectOption('#mode','sine');await page.click('#step');assert((await page.textContent('#settle')).includes('RMS'));await page.selectOption('#speed','0.25');await page.selectOption('#speed','1');
for(const size of [{width:390,height:844},{width:844,height:390}]){await page.setViewportSize(size);await page.waitForTimeout(100);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));for(const id of ['pause','reset','step','preset','aw','pulse','front','oblique','auto','target']){await page.locator('#'+id).scrollIntoViewIfNeeded();assert(await page.locator('#'+id).isVisible());const r=await page.locator('#'+id).boundingBox();assert(r.x>=0&&r.x+r.width<=size.width+.5,id);}await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:`/tmp/pid-${size.width}.png`,fullPage:true});}
await page.emulateMedia({reducedMotion:'reduce'});await page.reload();await page.waitForFunction(()=>window.pidDemo);a=await snapshot();assert(a.paused&&!a.auto);await page.waitForTimeout(100);assert.equal((await snapshot()).s.t,0);await page.keyboard.press('Tab');assert(await page.evaluate(()=>document.activeElement.tagName==='A'));
await page.evaluate(()=>window.dispatchEvent(new PageTransitionEvent('pagehide',{persisted:true})));a=await snapshot();await page.waitForTimeout(100);assert.equal((await snapshot()).frames,a.frames);await page.evaluate(()=>window.dispatchEvent(new PageTransitionEvent('pageshow',{persisted:true})));await page.waitForTimeout(100);assert((await snapshot()).frames>a.frames);await page.evaluate(()=>document.dispatchEvent(new Event('visibilitychange')));await page.click('#pause');await page.waitForTimeout(150);assert((await snapshot()).s.t<.2);
await page.evaluate(()=>window.dispatchEvent(new PageTransitionEvent('pagehide',{persisted:false})));a=await snapshot();assert(a.disposed);await page.waitForTimeout(100);assert.equal((await snapshot()).frames,a.frames);await page.evaluate(()=>pidDemo.dispose());assert(!errors.length,JSON.stringify(errors));
const failure=await browser.newPage();await failure.route('https://unpkg.com/**',r=>r.abort());await failure.goto(url);await failure.waitForSelector('#error:not([hidden])');await failure.close();const lost=await browser.newPage();await lost.goto(url);await lost.waitForFunction(()=>window.pidDemo);await lost.evaluate(()=>document.querySelector('#stage canvas').dispatchEvent(new Event('webglcontextlost',{cancelable:true})));assert((await lost.textContent('#error')).includes('그래픽'));assert(await lost.evaluate(()=>pidDemo.snapshot().disposed));await lost.close();console.log('PASS: actual RAF, all controls, pause/pulse/step/reset, presets, camera, responsive scroll reachability, reduced motion, keyboard, lifecycle events, dispose, CDN failure, context loss; console errors:',errors.length);
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
