const fs=require('fs'),vm=require('vm'),assert=require('assert');
const html=fs.readFileSync(__dirname+'/structural-resonance.html','utf8'),code=html.match(/<script id="physics">([\s\S]*?)<\/script>/)[1];const D=vm.runInNewContext(code+';Dynamics');
const m=D.model([1000],[100000]),h=1/960;assert(Math.abs(m.modes[0].frequency-10/(2*Math.PI))<1e-12);
let y=D.initial(m,[.01]),maxError=0;for(let i=0;i<9600;i++){y=D.step(m,.12,y,i*h,h,()=>0);const t=(i+1)*h,wd=10*Math.sqrt(1-.12**2),exact=.01*Math.exp(-1.2*t)*(Math.cos(wd*t)+1.2/wd*Math.sin(wd*t));maxError=Math.max(maxError,Math.abs(D.physical(m,y)[0]-exact));}assert(maxError<1e-8);
let staticY=D.initial(m,[0]);for(let i=0;i<30000;i++)staticY=D.step(m,.3,staticY,i*h,h,()=>-.1);const staticError=Math.abs(D.physical(m,staticY)[0]-100/100000);assert(staticError<1e-10);
let residual=0,orthogonal=0,maxOmega=0;for(const mass of [500,1000,2000])for(const ratio of [.5,1,2])for(const k of [50000,100000,200000]){const m=D.model([mass,mass,mass,mass*ratio],Array(4).fill(k));for(let i=0;i<4;i++){const p=m.modes[i];maxOmega=Math.max(maxOmega,p.omega);const kp=m.K.map(r=>D.dot(r,p.phi)),mp=p.phi.map((v,j)=>p.lambda*m.masses[j]*v);residual=Math.max(residual,Math.hypot(...kp.map((v,j)=>v-mp[j]))/Math.hypot(...kp));for(let j=0;j<4;j++)orthogonal=Math.max(orthogonal,Math.abs(p.phi.reduce((s,v,l)=>s+v*m.masses[l]*m.modes[j].phi[l],0)-(i===j?1:0)));}}
assert(residual<1e-8&&orthogonal<1e-8);const four=D.model([500,500,500,250],Array(4).fill(200000));const initial=D.initial(four,[0,0,0,.01]),e0=D.energy(four,initial);let undamped=initial,damped=initial,previous=e0;for(let i=0;i<9600;i++){undamped=D.step(four,0,undamped,i*h,h,()=>0);damped=D.step(four,.12,damped,i*h,h,()=>0);const e=D.energy(four,damped);assert(e<=previous+1e-12);previous=e;}const energyDrift=Math.abs(D.energy(four,undamped)/e0-1);assert(energyDrift<.001);
function run(step,duration,zeta=.3){let y=initial;const force=t=>-.02*(10*Math.PI)**2*Math.sin(10*Math.PI*t);for(let i=0;i<Math.round(duration/step);i++)y=D.step(four,zeta,y,i*step,step,force);assert(y.every(Number.isFinite));return y;}
const coarse=run(h,10),fine=run(h/2,10),reference=run(h/4,10);const norm=(a,b)=>Math.hypot(...a.map((x,i)=>x-b[i]));const convergence=norm(coarse,fine)/norm(fine,reference);assert(convergence>12&&convergence<20);for(const zeta of [0,.01,.3])run(h,120,zeta);
console.log(JSON.stringify({frequency:m.modes[0].frequency,analyticMaxError:maxError,staticError,residual,orthogonal,maxOmega,energyDrift,convergence,coarseFine:norm(coarse,fine),longRun:'120 s / 5 Hz / 20 mm / minimum mass / maximum stiffness / zeta 0,.01,.3 finite'},null,2));
fs.writeFileSync('/tmp/resonance-module.mjs',html.match(/<script type="module">([\s\S]*?)<\/script>/)[1]);
