const {chromium}=require('/home/bayta/.cache/ms-playwright-go/1.57.0/package');
const http=require('http'),fs=require('fs'),path=require('path'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{const file=path.join(root,decodeURIComponent(req.url.split('?')[0]));if(!file.startsWith(root+'/')){res.writeHead(403).end();return;}fs.readFile(file,(err,data)=>{if(err){res.writeHead(404).end();return;}res.setHeader('Content-Type',file.endsWith('.html')?'text/html;charset=utf-8':'text/plain');res.end(data);});});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({executablePath:'/snap/chromium/current/usr/lib/chromium-browser/chrome',headless:true,env:{...process.env,FONTCONFIG_FILE:'/tmp/abyssal-fonts.conf',LD_LIBRARY_PATH:'/snap/chromium/current/usr/lib/x86_64-linux-gnu:/snap/gnome-46-2404/current/usr/lib/x86_64-linux-gnu'},args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-dev-shm-usage']});
try{const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('404'))errors.push(m.text());});
const url=`http://127.0.0.1:${server.address().port}/linear-transform/linear-transform.html`;await page.goto(url);await page.waitForFunction(()=>window.linearLab,{timeout:120000});
const state=()=>page.evaluate(()=>linearLab.getState());const a=await state();assert(a.finite);assert.equal(a.playing,false);assert.equal(a.analysis.rank,3);
await page.screenshot({path:'/tmp/linear-transform-desktop.png'});
await page.selectOption('#preset','shear');assert.equal((await state()).analysis.symmetric,false);assert(await page.locator('#eigen').isDisabled());
await page.locator('#matrix input').first().fill('');await page.click('#apply');assert(await page.locator('#input-error').textContent());assert.deepEqual((await state()).target,[1,1.2,0,0,1,0,0,0,1]);
await page.selectOption('#preset','reflection');await page.locator('#progress').fill('0.5');let b=await state();assert.equal(b.analysis.rank,2);assert.equal(b.analysis.det,0);assert.equal(b.basis[0][3],0);assert(b.finite);
await page.selectOption('#preset','projection');assert.equal((await state()).analysis.rank,2);await page.locator('#eigen').check();assert((await state()).visible.eigen);
for(const preset of ['identity','stretch','shear','rotation','reflection','projection','symmetric']){await page.selectOption('#preset',preset);assert((await state()).finite);}const fields=page.locator('#matrix input');for(let i=0;i<9;i++)await fields.nth(i).fill('0');await page.click('#apply');assert.equal((await state()).analysis.rank,0);assert((await state()).finite);
for(const tiny of ['0.00001','1e-200']){for(let i=0;i<9;i++)await fields.nth(i).fill(i%4===0?tiny:'0');await page.click('#apply');assert.equal((await state()).analysis.rank,3);assert.notEqual(await page.locator('#det').textContent(),'0');}
await page.setViewportSize({width:721,height:1440});for(let i=0;i<9;i++)await fields.nth(i).fill('3');await page.click('#apply');await page.waitForTimeout(100);b=await state();assert(b.far>Math.hypot(...b.camera)+20);await page.setViewportSize({width:1440,height:1000});
await page.selectOption('#preset','symmetric');await page.locator('#progress').fill('0.3');b=await state();b.current.forEach((v,i)=>assert(Math.abs(v-(.7*[1,0,0,0,1,0,0,0,1][i]+.3*b.target[i]))<1e-12));for(let i=0;i<3;i++)for(let j=0;j<3;j++)assert(Math.abs(b.basis[i][3+j]-b.current[3*j+i])<1e-6);
await page.click('#auto');await page.click('#play');let start=await state();await page.waitForTimeout(600);let end=await state();assert(end.u>start.u);assert(end.angle>start.angle);await page.click('#play');start=await state();await page.waitForTimeout(300);assert.equal((await state()).u,start.u);assert.equal((await state()).angle,start.angle);
await page.click('#auto');await page.click('#play');start=await state();await page.waitForTimeout(300);assert((await state()).u>start.u);assert.equal((await state()).angle,start.angle);await page.click('#play');await page.selectOption('#speed','2');assert.equal((await state()).playing,false);
await page.click('#front');await page.waitForTimeout(100);assert.equal((await state()).camera[0],0);await page.click('#top');await page.waitForTimeout(100);assert.equal((await state()).camera[2],0);await page.click('#oblique');
await page.locator('#principal').uncheck();assert.equal((await state()).visible.principal,false);await page.click('#reset');assert.equal((await state()).u,1);assert.equal((await state()).view,'oblique');assert.equal((await state()).visible.principal,true);
await page.mouse.move(70,240);start=await state();await page.mouse.move(700,300);await page.waitForTimeout(100);assert.deepEqual((await state()).camera,start.camera);
for(const viewport of [{width:390,height:844},{width:844,height:390}]){await page.setViewportSize(viewport);await page.waitForTimeout(200);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),viewport.width);await page.locator('#apply').scrollIntoViewIfNeeded();for(let i=0;i<9;i++){const box=await fields.nth(i).boundingBox();assert(box.x>=0&&box.x+box.width<=viewport.width);}await fields.nth(0).fill('1.5');await page.click('#apply');assert.equal((await state()).target[0],1.5);await page.locator('#play').scrollIntoViewIfNeeded();await page.click('#play');await page.click('#play');await page.screenshot({path:`/tmp/linear-transform-${viewport.width}.png`});await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:`/tmp/linear-transform-${viewport.width}-top.png`});}
await page.emulateMedia({reducedMotion:'reduce'});await page.reload();await page.waitForFunction(()=>window.linearLab);assert.equal((await state()).auto,false);assert.equal((await state()).playing,false);start=await state();await page.waitForTimeout(250);assert.equal((await state()).u,start.u);
await page.evaluate(()=>dispatchEvent(new PageTransitionEvent('pagehide',{persisted:true})));assert.equal((await state()).suspended,true);await page.evaluate(()=>dispatchEvent(new PageTransitionEvent('pageshow',{persisted:true})));assert.equal((await state()).suspended,false);
await page.evaluate(()=>document.dispatchEvent(new Event('visibilitychange')));await page.waitForTimeout(100);assert((await state()).finite);
assert.equal(await page.locator('header a').getAttribute('href'),'../index.html');assert.equal((await page.request.get(`http://127.0.0.1:${server.address().port}/index.html`)).status(),200);assert.equal(errors.length,0,errors.join('\n'));
await page.evaluate(()=>linearLab.dispose());assert.equal((await state()).disposed,true);assert.equal(await page.locator('#stage canvas').count(),0);
const failure=await browser.newPage();await failure.route('https://unpkg.com/**',route=>route.abort());await failure.goto(url);await failure.waitForFunction(()=>!document.getElementById('error').hidden);assert((await failure.locator('#error').textContent()).includes('CDN'));await failure.close();
console.log('PASS: real RAF, matrix edits, invalid input, singular/zero, interpolation geometry, eigen gating, layers, play/pause/camera, presets/reset, desktop/mobile/landscape, reduced motion, synthetic lifecycle, disposal, CDN failure. Console errors: '+errors.length);
await page.close();}finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
