const {chromium}=require('/home/bayta/.cache/ms-playwright-go/1.57.0/package');
const fs=require('node:fs'),http=require('node:http'),assert=require('node:assert/strict');
const file=__dirname+'/truss-lab.html',errors=[];
const seam=`window.__test={renderer,scene,camera,bars:()=>bars,joints:()=>joints,point,render,advance,solve,dispose,resize,getModel:()=>model,result:()=>result,state:()=>({running,auto,view,cameraTime,disposed,last,position:loadX,raf}),resources:()=>({geometries:geometries.size,materials:materials.size}),fail:()=>{model.members=[];solve();}};`;
const server=http.createServer((req,res)=>{if(req.url==='/favicon.ico'){res.writeHead(204);return res.end();}res.setHeader('Content-Type','text/html');res.end(fs.readFileSync(file,'utf8').replace('reset();resize();render();restart();',seam+'reset();resize();render();restart();'));});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${server.address().port}/truss-lab/truss-lab.html`;
const browser=await chromium.launch({executablePath:'/snap/chromium/current/usr/lib/chromium-browser/chrome',headless:true,env:{...process.env,FONTCONFIG_FILE:'/tmp/abyssal-fonts.conf',LD_LIBRARY_PATH:'/snap/chromium/current/usr/lib/x86_64-linux-gnu:/snap/gnome-46-2404/current/usr/lib/x86_64-linux-gnu'},args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-dev-shm-usage']});
try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}});page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 await page.goto(url);await page.waitForFunction(()=>window.__test,{timeout:60000});
 const state=()=>page.evaluate(()=>__test.state());
 const input=async(id,value)=>page.locator('#'+id).evaluate((e,v)=>{e.value=v;e.dispatchEvent(new Event('input',{bubbles:true}));e.dispatchEvent(new Event('change',{bubbles:true}));},value);
 await page.waitForTimeout(1200);const initial=await page.evaluate(()=>({frames:__test.renderer.info.render.frame,calls:__test.renderer.info.render.calls,fps:document.getElementById('fps').textContent,displacement:__test.result().maxU}));assert(initial.frames>1&&initial.calls>0);console.log('actual RAF rendering',initial);
 await page.screenshot({path:'/tmp/truss-lab-desktop.png'});
 for(const name of ['triangle','pratt','warren']){await page.selectOption('#preset',name);assert((await page.evaluate(()=>__test.result().residual))<1e-8);await page.evaluate(()=>{const t=__test; t.render();t.result().bars.forEach((b,i)=>{const mesh=t.bars()[i],a=t.point(b.i),c=t.point(b.j);if(mesh.position.distanceTo(a.clone().add(c).multiplyScalar(.5))>1e-10||Math.abs(mesh.scale.y-a.distanceTo(c))>1e-10)throw Error('geometry mismatch');});});}
 await input('position',2);await input('load',20);assert.match(await page.locator('#leftR').textContent(),/15.00/);assert.match(await page.locator('#rightR').textContent(),/5.00/);
 const u=await page.evaluate(()=>__test.result().maxU);await input('elastic',100);assert(Math.abs(await page.evaluate(()=>__test.result().maxU)-u*2)<1e-12);await input('area',800);assert(Math.abs(await page.evaluate(()=>__test.result().maxU)-u)<1e-12);
 await page.selectOption('#colorMode','stress');assert.match(await page.locator('#scaleText').textContent(),/MPa/);await page.selectOption('#member','3');assert.match(await page.locator('#memberInfo').textContent(),/M4/);await input('deformation',100);
 await page.click('#oblique');assert.equal((await state()).view,'oblique');await page.screenshot({path:'/tmp/truss-lab-oblique.png'});
 await page.click('#front');await page.waitForTimeout(100);const clickPoint=await page.evaluate(()=>{__test.render();const p=__test.bars()[5].position.clone().project(__test.camera),r=__test.renderer.domElement.getBoundingClientRect();return {x:r.x+(p.x+1)*r.width/2,y:r.y+(1-p.y)*r.height/2};});await page.mouse.click(clickPoint.x,clickPoint.y);assert.equal(await page.locator('#member').inputValue(),'5');
 await page.click('#auto');await page.click('#play');await page.waitForTimeout(600);const moved=await state();assert(moved.position>2&&moved.cameraTime>0);await page.click('#play');const frozen=await state();await page.waitForTimeout(300);const frozen2=await state();assert.equal(frozen2.position,frozen.position);assert.equal(frozen2.cameraTime,frozen.cameraTime);
 await input('position',3);assert.equal((await state()).position,3);await page.click('#auto');await page.evaluate(()=>__test.render());const cam=await page.evaluate(()=>__test.camera.position.toArray());await page.mouse.move(500,400);await page.waitForTimeout(100);assert.deepEqual(await page.evaluate(()=>__test.camera.position.toArray()),cam);
 await page.selectOption('#speed','2');await page.evaluate(()=>{const t=__test;document.getElementById('play').click();t.advance(.25);document.getElementById('play').click();});assert(Math.abs((await state()).position-3.4)<1e-8);
 await input('load',0);assert.equal(await page.evaluate(()=>__test.result().maxU),0);await page.click('#reset');assert.equal((await state()).position,4);assert.equal(await page.locator('#load').inputValue(),'10');assert.equal(await page.locator('#preset').inputValue(),'warren');assert.equal((await state()).running,false);
 const frameIndependence=await page.evaluate(()=>{const t=__test,run=(n)=>{document.getElementById('reset').click();document.getElementById('play').click();for(let i=0;i<n;i++)t.advance(1/n);document.getElementById('play').click();return t.state().position;};return [run(60),run(144)];});assert(Math.abs(frameIndependence[0]-frameIndependence[1])<1e-12);assert(Math.abs(frameIndependence[0]-4.8)<1e-12);await page.click('#reset');
 const resources=await page.evaluate(()=>__test.resources());for(let i=0;i<12;i++){await page.selectOption('#preset',i%2?'warren':'pratt');}assert.deepEqual(await page.evaluate(()=>__test.resources()),resources);console.log('frame subdivision + bounded resources',frameIndependence,resources);
 await page.locator('#member').focus();await page.keyboard.press('ArrowDown');assert.equal(await page.locator('#member').inputValue(),'1');
 for(const viewport of [{width:390,height:844},{width:844,height:390}]){await page.setViewportSize(viewport);await page.waitForTimeout(150);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));for(const id of ['preset','position','load','elastic','area','play','reset','speed','member','deformation','front','oblique','auto']){await page.locator('#'+id).scrollIntoViewIfNeeded();const b=await page.locator('#'+id).boundingBox();assert(b.x>=0&&b.x+b.width<=viewport.width+.1&&b.y>=-.1&&b.y+b.height<=viewport.height+.1,id);}await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:`/tmp/truss-lab-${viewport.width}.png`});}
 await page.emulateMedia({reducedMotion:'reduce'});await page.reload();await page.waitForFunction(()=>window.__test);assert.equal((await state()).auto,false);assert.equal((await state()).running,false);
 await page.evaluate(()=>{window.dispatchEvent(new PageTransitionEvent('pagehide',{persisted:true}));});const frames=await page.evaluate(()=>__test.renderer.info.render.frame);await page.waitForTimeout(150);assert.equal(await page.evaluate(()=>__test.renderer.info.render.frame),frames);await page.evaluate(()=>window.dispatchEvent(new PageTransitionEvent('pageshow',{persisted:true})));await page.waitForTimeout(150);assert(await page.evaluate(()=>__test.renderer.info.render.frame)>frames);
 await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));});const hiddenFrames=await page.evaluate(()=>__test.renderer.info.render.frame);await page.waitForTimeout(150);assert.equal(await page.evaluate(()=>__test.renderer.info.render.frame),hiddenFrames);await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:false});document.dispatchEvent(new Event('visibilitychange'));});await page.waitForTimeout(150);assert(await page.evaluate(()=>__test.renderer.info.render.frame)>hiddenFrames);
 await page.evaluate(()=>__test.fail());assert(await page.locator('#error').isVisible());assert.equal(await page.evaluate(()=>__test.result()),null);assert.equal(await page.locator('#maxU').textContent(),'—');
 await page.evaluate(()=>window.dispatchEvent(new PageTransitionEvent('pagehide',{persisted:false})));assert.equal((await state()).disposed,true);assert.equal(await page.locator('#stage canvas').count(),0);
 assert.equal(errors.length,0,JSON.stringify(errors));
 const fail=await browser.newPage();await fail.route('https://unpkg.com/**',r=>r.abort());await fail.goto(url);await fail.waitForSelector('#error:not([hidden])');assert.match(await fail.locator('#error').textContent(),/CDN/);await fail.close();
 const noGL=await browser.newPage();await noGL.addInitScript(()=>{const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){if(type.startsWith('webgl'))return null;return original.call(this,type,...args);};});await noGL.goto(url);await noGL.waitForSelector('#error:not([hidden])');assert.match(await noGL.locator('#error').textContent(),/WebGL/);await noGL.close();
 const lost=await browser.newPage();await lost.goto(url);await lost.waitForFunction(()=>window.__test);await lost.evaluate(()=>__test.renderer.domElement.dispatchEvent(new Event('webglcontextlost',{cancelable:true})));assert(await lost.locator('#error').isVisible());assert(await lost.evaluate(()=>__test.state().disposed));await lost.close();
 console.log('PASS: presets, geometry, material/load controls, selection (pointer/keyboard), pause/resume, speed, zero load, reset, views, mobile/landscape scroll reachability, reduced-motion, synthetic visibility/BFCache, disposal, singular invalidation, CDN/WebGL failure; console errors: 0');
}finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
