const {chromium}=require('/home/bayta/.cache/ms-playwright-go/1.57.0/package');
const fs=require('fs'),http=require('http'),assert=require('assert');
const server=http.createServer((req,res)=>{if(req.url==='/favicon.ico'){res.writeHead(204);res.end();return;}res.setHeader('Content-Type','text/html');res.end(fs.readFileSync(__dirname+'/heat-diffusion.html'));});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({executablePath:'/snap/chromium/current/usr/lib/chromium-browser/chrome',headless:true,env:{...process.env,FONTCONFIG_FILE:'/tmp/abyssal-fonts.conf',LD_LIBRARY_PATH:'/snap/chromium/current/usr/lib/x86_64-linux-gnu:/snap/gnome-46-2404/current/usr/lib/x86_64-linux-gnu'},args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-dev-shm-usage']});
try{const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});const url=`http://127.0.0.1:${server.address().port}/heat-diffusion/heat-diffusion.html`;await page.goto(url);await page.waitForFunction(()=>window.heatDemo);const state=()=>page.evaluate(()=>heatDemo.state());await page.waitForTimeout(400);assert((await state()).time>0);await page.click('#pause');let st=await state();await page.waitForTimeout(200);assert.equal((await state()).time,st.time);await page.click('#step');assert(Math.abs((await state()).time-st.time-st.dt)<1e-9);await page.click('#reset');assert.equal((await state()).time,0);
for(const axis of ['X','Y','Z']){const before=await state();await page.selectOption('#axis',axis);await page.locator('#slice').fill('3');await page.locator('#slice').dispatchEvent('input');await page.waitForTimeout(70);assert.equal((await state()).axis,'XYZ'.indexOf(axis));assert.equal((await state()).slice,3);assert.equal((await state()).energy,before.energy);}await page.locator('#px').fill('23');await page.locator('#px').dispatchEvent('change');assert.equal((await state()).probe[0],23);
await page.selectOption('#preset','boundary');await page.locator('#hot').fill('120');await page.locator('#hot').dispatchEvent('change');assert.equal((await state()).time,0);await page.click('#step');await page.selectOption('#material','1');assert.equal((await state()).time,0);assert((await state()).dt>.7);await page.selectOption('#preset','source');assert((await state()).source);await page.click('#source');assert(!(await state()).source);await page.locator('#power').fill('5');await page.locator('#power').dispatchEvent('input');await page.selectOption('#material','0');await page.selectOption('#speed','200');await page.selectOption('#view','auto');const cam=(await state()).camera;await page.waitForTimeout(200);assert.deepEqual((await state()).camera,cam);await page.click('#pause');await page.waitForTimeout(500);assert((await state()).time>0);await page.click('#pause');assert.notDeepEqual((await state()).camera,cam);await page.selectOption('#view','front');await page.waitForTimeout(100);assert.equal((await state()).camera[0],0);assert.equal((await state()).camera[1],0);await page.selectOption('#view','oblique');await page.waitForTimeout(100);const fixed=(await state()).camera;await page.mouse.move(200,200);await page.waitForTimeout(100);assert.deepEqual((await state()).camera,fixed);
await page.selectOption('#preset','spot');await page.selectOption('#axis','Z');await page.locator('#slice').fill('8');await page.locator('#slice').dispatchEvent('input');await page.locator('#px').fill('12');await page.locator('#px').dispatchEvent('change');await page.screenshot({path:'/tmp/heat-desktop.png',fullPage:true});assert((await state()).renderCalls>0);
for(const [width,height] of [[390,844],[844,390]]){await page.setViewportSize({width,height});await page.waitForTimeout(200);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));for(const id of ['pause','reset','step','preset','material','hot','cold','source','axis','slice','px','py','pz','speed','view']){await page.locator('#'+id).scrollIntoViewIfNeeded();const b=await page.locator('#'+id).boundingBox();if(!(b.x>=-1&&b.x+b.width<=width+1&&b.y>=-1&&b.y+b.height<=height+1)){await page.screenshot({path:'/tmp/heat-bounds-fail.png',fullPage:true});console.log({id,width,height,b});}assert(b.x>=-1&&b.x+b.width<=width+1&&b.y>=-1&&b.y+b.height<=height+1,id);}await page.screenshot({path:`/tmp/heat-${width}.png`,fullPage:true});}
await page.emulateMedia({reducedMotion:'reduce'});await page.reload();await page.waitForFunction(()=>window.heatDemo);assert((await state()).paused);assert(!(await state()).auto);await page.evaluate(()=>{window.dispatchEvent(new PageTransitionEvent('pagehide',{persisted:true}));});const frozen=(await state()).time;await page.waitForTimeout(100);assert.equal((await state()).time,frozen);await page.evaluate(()=>window.dispatchEvent(new PageTransitionEvent('pageshow',{persisted:true})));await page.click('#pause');await page.waitForTimeout(200);assert((await state()).time>frozen);await page.evaluate(()=>document.dispatchEvent(new Event('visibilitychange')));assert(!errors.length,JSON.stringify(errors));await page.evaluate(()=>heatDemo.dispose());assert((await state()).disposed);const end=(await state()).time;await page.waitForTimeout(100);assert.equal((await state()).time,end);
const failed=await browser.newPage();await failed.route('https://unpkg.com/**',r=>r.abort());await failed.goto(url);await failed.waitForSelector('#error:not([hidden])');await failed.close();const lost=await browser.newPage();await lost.goto(url);await lost.waitForFunction(()=>window.heatDemo);await lost.evaluate(()=>document.querySelector('#stage canvas').dispatchEvent(new Event('webglcontextlost',{cancelable:true})));await lost.waitForSelector('#error:not([hidden])');assert(await lost.evaluate(()=>heatDemo.state().disposed));console.log(JSON.stringify({result:'PASS',checks:'actual RAF render, pause/resume/reset/step, all controls, maximum speed, static/automatic camera, 3 slice axes, probe, desktop/mobile/landscape scroll reachability, reduced motion, synthetic BFCache/visibility events, dispose, CDN failure, context-loss handler',errors,screenshots:['/tmp/heat-desktop.png','/tmp/heat-390.png','/tmp/heat-844.png']},null,2));
}finally{await browser.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
