const {chromium}=require('/home/bayta/.cache/ms-playwright-go/1.57.0/package'),fs=require('fs'),http=require('http'),assert=require('assert/strict');const html=fs.readFileSync(__dirname+'/lorenz-attractor.html');const server=require('../tests/static-server.cjs')();
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({executablePath:'/snap/chromium/current/usr/lib/chromium-browser/chrome',headless:true,env:{...process.env,FONTCONFIG_FILE:'/tmp/abyssal-fonts.conf',LD_LIBRARY_PATH:'/snap/chromium/current/usr/lib/x86_64-linux-gnu:/snap/gnome-46-2404/current/usr/lib/x86_64-linux-gnu'},args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-dev-shm-usage']});try{const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});const url=`http://127.0.0.1:${server.address().port}/lorenz-attractor/lorenz-attractor.html`;await page.goto(url);await page.waitForFunction(()=>window.__lorenz,{},{timeout:90000});const state=()=>page.evaluate(()=>__lorenz.snapshot());await page.waitForTimeout(1300);assert((await state()).time>0);await page.click('#pause');let s=await state();await page.waitForTimeout(250);assert.equal((await state()).time,s.time);assert.equal((await state()).angle,s.angle);await page.click('#step');assert(Math.abs((await state()).time-s.time-.005)<1e-12);await page.click('[data-view=xy]');let camera=await page.evaluate(()=>__lorenz.camera.position.toArray());await page.click('#auto');assert.notDeepEqual(await page.evaluate(()=>__lorenz.camera.position.toArray()),camera);await page.click('#auto');camera=await page.evaluate(()=>__lorenz.camera.position.toArray());await page.mouse.move(500,400);await page.waitForTimeout(100);assert.deepEqual(await page.evaluate(()=>__lorenz.camera.position.toArray()),camera);
await page.selectOption('#speed','2');assert.equal((await state()).speed,2);await page.click('#reset');assert.equal((await state()).time,0);for(const preset of ['0.5','10','28']){await page.selectOption('#preset',preset);assert.equal(await page.evaluate(()=>__lorenz.model.p.rho),Number(preset));assert.equal((await state()).time,0)}for(const id of ['sigma','rho','beta','epsilon']){await page.locator('#'+id).evaluate(el=>{el.value=el.max;el.dispatchEvent(new Event('input',{bubbles:true}))});assert.equal((await state()).time,0)}assert.deepEqual(await page.evaluate(()=>__lorenz.model.p),{sigma:20,rho:50,beta:4});await page.selectOption('#preset','28');await page.locator('#epsilon').evaluate(el=>{el.value=-5;el.dispatchEvent(new Event('input',{bubbles:true}))});
// Deterministic fast-forward verifies wrapped rendering, not performance.
await page.evaluate(()=>{for(let i=0;i<13000;i++)__lorenz.model.step();document.querySelector('#length').dispatchEvent(new Event('change'))});await page.waitForTimeout(200);const wrap=await page.evaluate(()=>{const m=__lorenz.model,g=__lorenz.lines[0].geometry,a=g.attributes.position.array;let error=0;for(let i=0;i<m.path.count-1;i++){for(let j=0;j<2;j++){const v=m.path.at(i+j)[0],actual=Array.from(a.slice(i*6+j*3,i*6+j*3+3)),expected=[v[0],v[2],v[1]];for(let k=0;k<3;k++)error=Math.max(error,Math.abs(actual[k]-expected[k]))}}return {count:m.path.count,draw:g.drawRange.count,error}});assert.equal(wrap.count,12000);assert.equal(wrap.draw,23998);assert(wrap.error<4e-6);await page.screenshot({path:'/tmp/lorenz-desktop.png'});await page.selectOption('#traces','a');await page.waitForTimeout(100);assert.deepEqual(await page.evaluate(()=>__lorenz.lines.map(l=>l.visible)),[true,false]);await page.selectOption('#traces','b');await page.waitForTimeout(100);assert.deepEqual(await page.evaluate(()=>__lorenz.lines.map(l=>l.visible)),[false,true]);await page.selectOption('#traces','both');await page.selectOption('#scale','linear');await page.selectOption('#length','2000');await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>__lorenz.lines[0].geometry.drawRange.count),3998);await page.selectOption('#scale','log');
for(const size of [{width:390,height:844},{width:844,height:390}]){await page.setViewportSize(size);await page.waitForTimeout(150);assert(await page.evaluate(()=>document.documentElement.scrollWidth===innerWidth));for(const id of ['pause','reset','step','speed','auto','preset','sigma','rho','beta','epsilon','traces','scale','length']){await page.locator('#'+id).scrollIntoViewIfNeeded();const b=await page.locator('#'+id).boundingBox();assert(b.x>=0&&b.x+b.width<=size.width+1&&b.y>=-1&&b.y+b.height<=size.height+1,id)}await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:`/tmp/lorenz-${size.width}.png`,fullPage:true})}
await page.emulateMedia({reducedMotion:'reduce'});await page.reload();await page.waitForFunction(()=>window.__lorenz);assert((await state()).paused);assert(!(await state()).auto);await page.click('#pause');await page.waitForTimeout(250);assert((await state()).time>0);await page.evaluate(()=>window.dispatchEvent(new PageTransitionEvent('pagehide',{persisted:true})));const hiddenTime=(await state()).time;await page.waitForTimeout(150);assert.equal((await state()).time,hiddenTime);await page.evaluate(()=>window.dispatchEvent(new PageTransitionEvent('pageshow',{persisted:true})));await page.waitForTimeout(150);assert((await state()).time>hiddenTime);await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'))});const t=(await state()).time;await page.waitForTimeout(150);assert.equal((await state()).time,t);await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:false});document.dispatchEvent(new Event('visibilitychange'))});await page.waitForTimeout(150);assert((await state()).time>t);const rendering=await page.evaluate(()=>({frames:__lorenz.renderer.info.render.frame,calls:__lorenz.renderer.info.render.calls,contextLost:__lorenz.renderer.getContext().isContextLost()}));assert(!rendering.contextLost);assert.equal(errors.length,0,errors.join('\n'));await page.evaluate(()=>window.dispatchEvent(new PageTransitionEvent('pagehide',{persisted:false})));assert((await state()).disposed);assert.equal(await page.locator('#stage canvas').count(),0);
// Context loss must release resources and stay stopped after lifecycle events.
const lost=await browser.newPage();await lost.goto(url);await lost.waitForFunction(()=>window.__lorenz);
await lost.evaluate(()=>__lorenz.renderer.getContext().getExtension('WEBGL_lose_context').loseContext());
await lost.waitForSelector('#error:not([hidden])');
const lostState=await lost.evaluate(()=>__lorenz.snapshot());
const lostFrames=await lost.evaluate(()=>__lorenz.renderer.info.render.frame);
await lost.evaluate(()=>{document.dispatchEvent(new Event('visibilitychange'));window.dispatchEvent(new PageTransitionEvent('pageshow',{persisted:true}));document.querySelector('#reset').click();});
await lost.waitForTimeout(200);
assert.equal((await lost.evaluate(()=>__lorenz.snapshot())).time,lostState.time,'context loss must not resume simulation after visibility/pageshow events');
assert(lostState.disposed,'context loss must dispose the scene');
assert.equal(await lost.locator('#stage canvas').count(),0);
assert.equal(await lost.evaluate(()=>__lorenz.renderer.info.render.frame),lostFrames);
await lost.close();
const fail=await browser.newPage();await fail.route('https://unpkg.com/**',r=>r.abort());await fail.goto(url);await fail.waitForSelector('#error:not([hidden])');await fail.close();const noGL=await browser.newPage();await noGL.addInitScript(()=>{const get=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){if(type.startsWith('webgl'))return null;return get.call(this,type,...args)}});await noGL.goto(url);await noGL.waitForSelector('#error:not([hidden])');console.log(JSON.stringify({wrap,rendering,errors,checks:'real RAF, pause/resume/step/reset, presets, parameter maxima, speed selection, static mouse, paused camera switch, trace modes, graph modes, ring rendering, length, desktop/mobile/landscape, reduced motion, simulated visibility/BFCache events, disposal, real WebGL context loss and no lifecycle restart, CDN/WebGL failure'},null,2));}finally{await browser.close();await new Promise(r=>server.close(r))}})().catch(e=>{console.error(e);server.close();process.exitCode=1});
